### ISSUE TITLE
RVM Syntax Error on Powder Open -- Ruby 1.8.7

### ISSUE THREAD

**Issue by suzumakes** [rodreegez/powder#119]
/Users/user/.rvm/gems/ruby-1.8.7-head/bin/powder:23:in `load': /Users/user/.rvm/gems/ruby-1.8.7-head/gems/powder-0.3.0/bin/powder:24: undefined (?...) sequence: /^(?<major_version>\d+)\.(?<minor_version>\d+)/ (SyntaxError)
    from /Users/user/.rvm/gems/ruby-1.8.7-head/bin/powder:23
    from /Users/user/.rvm/gems/ruby-1.8.7-head/bin/ruby_executable_hooks:15

Ruby 1.8.7 and Rails 2.3.5 app. Just encountered this so I'll flesh this out more if I find more.

**Comment by corinnekunze** [comment]
+1, 
I'm having this issue as well. Our app is Ruby 1.8.7

**Comment by amitrai99** [comment]
Same here

**Comment by rolandcedo** [comment]
+1
Same here, same version as those above (1.8.7). Version issue I'm assuming?

**Comment by philnash** [comment]
Hey all, I'd absolutely recommend you upgrade your Ruby version on your apps. Maintenance on Ruby 1.8.7 stopped years ago now so it does not receive any security updates. Ruby 1.9.x is also out of support as is Ruby 2.0.x.

You need to seriously consider upgrading Ruby to at least version 2.1.x so that you can get security updates and keep your applications safe.

Ideally powder would work for you, but fixing it for such an out of date version of Ruby just seems inadvisable. I'm going to close this issue and pray you all update your Rubies.
